version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: npm run dev:start
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
      - PORT=8080
    volumes:
      - ./:/usr/src/app
